export const enum HrRequestType {
  LEAVE_APPLICATION = "LEAVE_APPLICATION",
  SALARY_ADVANCE = "SALARY_ADVANCE",
  RESIGNATION = "RESIGNATION",
  TRANSFER_REQUEST = "TRANSFER_REQUEST",
  PROMOTION_REQUEST = "PROMOTION_REQUEST",
  TRAINING_REQUEST = "TRAINING_REQUEST",
  BULK_REGULARIZATION = "BULK_REGULARIZATION",
  WEEKLY_OFF = "WEEKLY_OFF"
}
